#配置端口号
server:
  port: 8088
spring:
  application:
    name: hbuy-web
  #配置访问页面路径的前后缀
  servlet:
    multipart:
      #单个文件上传最大大小
      max-file-size: 300MB
      #请求时的文件大小（多个）
      max-request-size: 400MB
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    #配置访问静态资源
    static-path-pattern: /**
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///k9503_buy?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置mybatis
mybatis:
  type-aliases-package: com.java.web.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml

#注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka